{
  "name": "Dia D - A Permanência do Registro",
  "targets": [
    "linkedin"
  ],
  "content": "Permanência do Registro: por que esquecemos as decisões que mudaram nossa vida?\n\nVivemos registrando tudo.\n\nFotos.\nMensagens.\nPlanilhas.\nCompromissos.\nMetas.\n\nMas quase ninguém registra aquilo que realmente muda o rumo de uma vida: as decisões.\n\nUma decisão importante raramente nasce em um único instante. Ela costuma ser construída por semanas, meses ou até anos de observação, dúvidas, conversas e pequenas escolhas silenciosas.\n\nO problema é que, depois que a decisão é tomada, nossa memória reescreve a história. Esquecemos o contexto, os medos, os argumentos e os sinais que estavam diante de nós. Quando enfrentamos uma situação semelhante no futuro, temos a sensação de estar começando do zero.\n\nFoi dessa inquietação que nasceu o e-book 'A Permanência do Registro'.\n\nO livro propõe uma ideia simples, mas poderosa: registrar não apenas o que aconteceu, mas por que uma decisão foi tomada.\n\nUm registro consciente cria continuidade. Ele permite que a experiência acumulada se transforme em patrimônio intelectual, em vez de desaparecer com o tempo.\n\nNas empresas, isso reduz a perda de conhecimento quando pessoas mudam de função.\n\nNa vida pessoal, evita que repitamos erros por falta de memória.\n\nNa liderança, transforma decisões isoladas em um processo que pode ser revisitado, compreendido e aprimorado.\n\nVivemos em uma época em que a informação é abundante, mas o discernimento continua sendo escasso.\n\nTalvez o verdadeiro patrimônio não seja aquilo que possuímos, mas aquilo que conseguimos compreender sobre nossas próprias escolhas.\n\nEsse é o convite deste livro.\n\nNão apenas lembrar.\n\nMas construir uma memória capaz de continuar produzindo valor muitos anos depois.\n\nPorque decisões passam. O registro permanece.\n\n📖 E-book: A Permanência do Registro.\n\nSe este tema faz sentido para você, acompanhe a Spiral Codes. Estamos desenvolvendo tecnologias voltadas ao registro consciente de decisões, preservação do conhecimento e inteligência aplicada à tomada de decisão.\n\n#PermanenciaDoRegistro #TomadaDeDecisao #Lideranca #Conhecimento #Gestao #Memoria #SpiralCodes #Inovacao #InteligenciaArtificial",
  "assets": [
    "Permanencia_do_Registro_Capa.png"
  ]
}